### ISSUE TITLE
Load an VTT file

### ISSUE THREAD

**Issue by bozkurtnevzat** [siloor/youtube.external.subtitle#3]
It would be nice if it was added.

**Comment by siloor** [comment]
The problem with VVT is, that the script doesn't add subtitle the html5 way to the video.
It is like this, because the script doesn't have permission to add anything into the youtube video player iframe.

But a VVT file can be parsed easily. You just need to get the subtitles and the timings from it, and provide it to the script in the needed format. Parsing an SRT file is a very good example for this.
